### ISSUE TITLE
Create grok patterns

### ISSUE THREAD

**Issue by igabriel85** [igabriel85/IeAT-DICE-Repository#10]
Create custom patterns in grok for metrics2 file sink outputs.

For example:
%{EXPNOT}=[-+]?[0-9]*.?[0-9]+([eE][-+]?[0-9]+)? -> for exponential (scientific) notation

**Comment by mneagul** [comment]
(?<mymatch>[-+]?\d_.?\d_(?<exponent>[eE]-\d*\d?))

**Comment by igabriel85** [comment]
Issue temporarily fixed with %{DATA:...}, grok filter no longer fails.
