### ISSUE TITLE
Feature request: removal or replacement of nodes

### ISSUE THREAD

**Issue by matejart** [igabriel85/IeAT-DICE-Repository#171]
We are using DMon as a persistent service in the cluster. The applications being deployed and their nodes get registered from Cloudify. We could also unregister or remove them when we tear the application down, but that does not seem to be possible.

In practice, DMon preserves nodes and their roles even after the actual nodes are already gone. Since the test bed platform recycles the IPs it is possible that it provisions a previously seen IP again. This causes an exception in the DMon:

```
IntegrityError: (IntegrityError) UNIQUE constraint failed: db_nodes.nodeIP u'INSERT INTO db_nodes ("nodeFQDN", "nodeIP", "nodeUUID", "nodeOS", "nUser", "nPass", nkey, "nRoles", "nStatus", "nMonitored", "nCollectdState", "nLogstashForwState", "nLogstashInstance", timestamp) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)' (u'a16860-storm-00163e32ea3d', u'109.231.122.199', None, u'ubuntu', None, None, None, 'unknown', 0, 0, 'None', 'None', u'109.231.122.158', '2017-02-21 08:01:40.092875')
```

It would be great if there was a way to remove or replace nodes already registered in the DMon.

**Comment by igabriel85** [comment]
You can delete any registered node based on its FQDN:

`DELETE /dmon/v1/overlord/nodes/{FQDN}`

Or you can modify the ip of a given NODE by issuing:

`PUT v1/overlord/nodes` only the FQDN CANNOT change the rest of the settings are changable.

**Comment by matejart** [comment]
Thank you for this suggestion. We did think it is what we'd needed, but unfortunately it doesn't work in our setting. Looking at the [implementation of the routine](https://github.com/dice-project/DICE-Monitoring/blob/master/src/pyDMON.py#L1849-L1887) it is apparent that dmon will try to connect to the node to be deleted and manipulate the services there. The problem is, that we get to call this operation after the node has already been shut down, deleted and gone. So the call always fails before doing anything.

Given this context, it would be nice to have a query parameter or some other way to force deletion of a FQDN entry from DMon.

On a different note, does this routine commit its changes? Does the `db.session.commit()` happen somewhere else?

**Comment by igabriel85** [comment]
I have added a new resources:

`DELETE -> /dmon/v1/overlord/nodes/list`

it accepts the following json:

```json
{
"Nodes" : ["node1ID", "node2ID"]
}

```
It returns the following json:

```json
{
  "Invalid": [],
  "Stopped": {"node1ID":  "node1IP"},
  "Unavailable": {"node2ID": "node2IP"},
  "Valid": {"node1ID":  "node1IP",  "node2ID": "node2IP"}
}
```

where Invalid is the list of nodes not registered to _DMon_, Valid represents the valid nodes from _DMon_, Stopped the agents stopped by _DMon_, Unavailable the agents not stopped by _DMon_ but are unreachable. It is not important who shuts down the _dmon-agents_ it can be the Deployment service or _DMon_.

The resource:

`DELETE -> /dmon/v1/overlord/nodes/<nodeID>`

will first check if the _dmon-agent_ is running, if it is it will issue the shutdown command and then deregister the node, if the agent  is not reachable it will simply deregister the node.

**Comment by matejart** [comment]
I can confirm that this is now working. Thank you!
